const industryTrack = [
    {
        title: "Anomaly Detection and Diagnosis of Vehicle Steering Systems Using a Knowledge Graph-based Approach",
        authors: "Qiushi Cao, Patelis Alexandros and Irlan Grangel González",
        abstract: "In the automotive industry, data-driven techniques have been widely used for the early detection of vehicle field issues. During data analysis processes, data heterogeneity is a crucial pain point that causes huge manual effort and time delay. To mitigate this pain point, in this paper we demonstrate a knowledge graph-based approach for the early detection of vehicle technical issues for automotive steering systems. The proposed approach enables semantic data integration, by which the efficiency of data Extract, Transform, Load (ETL) process is significantly improved. Based on the developed knowledge graph system, data visualization dashboards and Large Language Model (LLM) solutions can be easily developed to gain insights for failure-cause-effect analysis. The proposed knowledge graph-based approach has gained significant efficiency improvement. The time and manual efforts for data ETL and integration have been reduced up to 70\\%. The use of standardized domain ontologies enables the re-usability of the proposed approach for other use cases or products. Our work highlights the importance of industrial knowledge graphs for tackling data heterogeneity and data quality issues when developing data-driven applications."
    },
    {
        title: "Building a Canonical Register of Public Sector Entities: Semantic Linking of Procurement Data at Scale",
        authors: "Roberto Avogadro, Ian Makgill, Aleena Thomas, Ahmet Soylu and Dumitru Roman",
        abstract: "Public procurement generates over $13 trillion annually, yet data about public buyers and suppliers remains fragmented, inconsistent, and difficult to link across jurisdictions. This paper presents a practical industrial solution developed by Spend Network within the European project enRichMyData to semantically enrich and reconcile procurement data at scale. The proposed pipeline combines large language models (LLMs) with knowledge graphs (KGs) to create and maintain a canonical register of public sector entities. It supports multilingual, cross-border integration and is designed to serve both public transparency and commercial applications.The pipeline has been evaluated on a manually curated benchmark of 1,000 procurement-related entities and demonstrates high precision and scalability in real-world settings"
    },
    {
        title: "Knowledge-Augmented Security Risk Identification for OT Container Deployments",
        authors: "Yannick Landeck, Dian Balta, Tomas Bueno Momcilovic, Martin Wimmer and Christian Knierim",
        abstract: "Container deployments in operational technology (OT) environments pose unique security challenges, especially when privileged configurations are used. Traditional risk identification methods often fall short in addressing the complexity, dynamic nature, and interdisciplinary collaboration required in these settings. We propose a knowledge augmentation approach that combines semantic modelling, automated reasoning, and tool support to enhance security risk identification. Our approach is demonstrated through an industrial case study, highlighting its practical application. We also examine how large language models (LLMs) can support the instantiation and integration of the approach, improving usability and scalability."
    },
    {
        title: "Empowering Supply Chain Risk Monitoring with Ontology-Guided Knowledge Graph Extraction by LLMs",
        authors: "Shuhan Zheng, Keita Mizushina and Ken Naono",
        abstract: "With business globalization and increasing product complexity, companies often operate supply chains distributed around the world. Such globally distributed supply chains face various disruption risks, highlighting the need for procurement officers to effectively monitor these risks. A popular paradigm is to apply information extraction technologies to open data for risk extraction. Here, we introduce an ontology-guided method for supply chain risk extraction that leverages large language models. Our method iteratively extracts a supply chain risk knowledge graph from unstructured open data, guided by a user-specified ontology. We also developed knowledge graph verification and formatting modules. Our wholistic methods enable consistent and automated identification and extraction of risk knowledge, thereby empowering procurement officers to monitor supply chain risks."
    },
    {
        title: "Semantic Technology in Your Pocket",
        authors: "Peter Crocker, Ian Horrocks and Yavor Nenov",
        abstract: "In January 2025, Samsung announced the launch of the Personal Data Engine (PDE) on their flagship Galaxy S25 smartphone. The PDE uses semantic technology in the form of the RDFox Knowledge Graph system to provide on-device AI capabilities to client applications. This almost certainly represents the largest ever deployment of semantic technology, with millions of users now carrying a semantic reasoning engine in their pocket."
    },
    {
        title: "RODEOS — Robotic Data Ecosystem Semantic Model: Bridging Siloed Robot Systems",
        authors: "Maximilian Stäbler, Lukas Sohlbach, Felix Weidinger, Steffen Turnbull, Jorge Marx-Goméz, Chris Schlueter-Langdon and Frank Köster",
        abstract: "Industry robotics across automotive paint shops, pharmaceutical clean-rooms, and e-commerce warehouses still relies on bespoke data mappings: every new robot arrives with proprietary file formats, capability vocabularies, and safety descriptors, forcing engineering teams into multi-week manual integration cycles. To address this cost and agility gap, we introduce RODEOS—RObotic Data EcOsystem Semantic Model, an emerging, vendor-neutral semantic blueprint co-defined by a consortium of 24 industrial partners. RODEOS extends the W3C DCAT-3 core with robotics-specific classes for raw data, model assets, and executable services, while preserving the lightweight authoring demands voiced in interviews with 17 experts drawn from research institutes, industrial end-users, robotics and automation suppliers, system integrators, IT-infrastructure providers, and the machinery-industry association—thereby capturing a truly holistic cross-domain requirements profile. We propose a prototype “semantic assistant’’ based on large language models to translate domain narratives into candidate semantic descriptions, enabling non-ontologists to curate the descriptions interactively."
    },
    {
        title: "FAIR Vocabulary Management at Scale: TERN's Implementation for Ecological Data Integration",
        authors: "Junrong Yu, Javier Sanchez Gonzalez, Edmond Chuc and Siddeswara Mayura Guru",
        abstract: "The Terrestrial Ecosystem Research Network (TERN) is Australia's national collaborative research infrastructure that collects, collates, and publishes key terrestrial ecosystem parameters across space and time. TERN observes ecosystems across multiple scales using satellite remote sensing, drones, in situ sensors, and human observations, whilst also publishing data from partnering institutes. This multi-source approach creates significant data management challenges, particularly in harmonising data from various sources. Most published datasets contain parameter names without adequate documentation about their meaning, and the same parameters are occasionally measured at different scales. Machine-readable controlled vocabularies provide the foundation for semantic interoperability, enabling data exchange with a shared understanding of the meaning of terms used. This paper describes the development and management of controlled vocabularies in the context of the data infrastructure managed by TERN. In addition, the paper provides an overview of different vocabulary types developed and their use in downstream applications."
    },
    {
        title: "An Explainable Natural Language Framework for Identifying and Notifying Target Audiences In Enterprise Communication",
        authors: "Vítor Lourenço, Mohnish Dubey, Yunfei Bai, Audrey Depeige and Vivek Jain",
        abstract: "In large-scale maintenance organizations, identifying subject matter experts and managing communications across complex entities relationships poses significant challenges that traditional communication approaches fail to address effectively. We propose a novel framework that combines RDF graph databases with LLMs to process natural language queries for precise audience targeting, while providing transparent reasoning through a planning-orchestration architecture. Our solution enables users to formulate intuitive queries about equipment, manufacturers, maintenance engineers, and facilities, delivering explainable results that maintain trust in the system while improving communication efficiency across the organization."
    },
    {
        title: "Mitigating Undesired Conditions in Flexible Production with Product-Process-Resource Asset Knowledge Graphs",
        authors: "Petr Novak, Stefan Biffl, Marek Obitko and Petr Kadera",
        abstract: "Contemporary industrial cyber-physical production systems (CPPS) composed of robotic workcells face significant challenges in the analysis of undesired conditions due to the flexibility of Industry 4.0 that disrupts traditional quality assurance mechanisms. This paper presents a novel industry-oriented semantic model called Product-Process-Resource Asset Knowledge Graph (PPR-AKG), which is designed to analyze and mitigate undesired conditions in flexible CPPS. Built on top of the well-proven Product-Process-Resource (PPR) model originating from ISA-95 and VDI-3682, a comprehensive OWL ontology addresses shortcomings of conventional model-driven engineering for CPPS, particularly inadequate undesired condition and error handling representation. The integration of semantic technologies with large language models (LLMs) provides intuitive interfaces for factory operators, production planners, and engineers to interact with the entire model using natural language. Evaluation with the use case addressing electric vehicle battery remanufacturing demonstrates that the PPR-AKG approach efficiently supports resource allocation based on explicitly represented capabilities as well as identification and mitigation of undesired conditions in production. The key contributions include (1) a holistic PPR-AKG model capturing multi-dimensional production knowledge, and (2) the useful combination of the PPR-AKG with LLM-based chatbots for human interaction."
    },
    {
        title: "Graph-Driven Validation Framework of Clinical Study Reports Using Semantic Technologies",
        authors: "Hanuragav Muthiah Giri and Gopinath Viswanathan",
        abstract: "Regulators demand that every listing, summary table and figure in a clinical-study report be consistent and traceable to raw observations. Traditional dual-programming in SAS or Python breaks down when schemas drift, while relational warehouses lose provenance. This paper outlines a knowledge-graph pipeline where an OWL/SHACL ontology governs validation, YAML mappings drive deterministic ETL, and GraphDB enforces constraints. The approach removes repetitive QC, surfaces discrepancies early and gives auditors click-through lineage from any published number to its source."
    },
    {
        title: "Exploring Semantic-Enhanced Property Graphs in Network Operations",
        authors: "Beyza Yaman, Michael Mackey, Peter Cautley and Declan O'Sullivan",
        abstract: "Telecommunication networks face significant challenges in performing root cause analysis due to their complexity, data heterogeneity, and high-volume event streams. Traditional semantic models like RDF and flexible property graph models such as LPG offer partial solutions but fall short when applied individually. This paper investigates the Semantic-enhanced Programmable Graph (SPG) approach, specifically through the OpenSPG engine, which integrates the structural advantages of property graphs with semantic constraints inspired by RDF ontologies. We evaluate its applicability in a telecom root cause analysis use case, comparing it to RDF-based modeling. Our findings investigate the applicability of OpenSPG in operational modeling and its limitations in maturity and tooling, offering insights for future semantic-enabled network management solutions."
    },
    {
        title: "Schema-Constrained Grammar-Guided Generation of GQL Queries from Natural Language",
        authors: "Andre Melo and Jeff Z. Pan",
        abstract: "Graph databases provide a robust foundation for storing and querying knowledge graphs, making them well-suited for powering intelligent personal assistants. Translating natural language into graph query languages (NL2GQL) enables these assistants to answer user queries by leveraging personal data stored as graphs. To preserve user privacy, on-device processing is preferred, but it comes with strict computational and memory constraints. A major challenge in this setting is ensuring that generated queries comply with user-specific, often custom, graph schemata. In this paper, we explore the business value and challenges of NL2GQL translation in a privacy-sensitive, resource-constrained setting, and propose schema-constrained grammar-guided generation as a potential solution to address these challenges."
    },
    {
        title: "Building Hierarchy-Aware Knowledge Graphs: Ontology-Grounded Triple Extraction with LLMs",
        authors: "Kudzai Sauka, Gianluigi Bardelloni, Frederik Situmeang and Jigsa Bulto",
        abstract: "This paper introduces a hierarchy-aware framework, Document_Preprocessing-Extract-Resolve-Merge-Canonicalize (DERMC), for constructing knowledge graphs using large language models (LLMs). It addresses the limitations of naive LLM prompting in creating a knowledge graph, which often results in redundancy, LLM cognitive overload, and inconsistencies across languages. Building on the Extract-Define-Canonicalize (EDC) paradigm, our approach integrates multilingual coreference resolution, hierarchical document parsing, and a RAG-MCP-inspired schema retriever that dynamically narrows candidate relations for each document context, thereby reducing the size of the LLM prompt. The system supports both commercial and local LLM backends, allowing flexible deployment. Preliminary results show improved alignment between flat and hierarchical parsing modes. Full-scale experiments and evaluations, including assessments by industry and knowledge representation experts, are planned to validate performance and quality in enterprise contexts."
    },
    {
        title: "RAGulating Compliance: A Multi-Agent Knowledge Graph for Regulatory Compliance QA",
        authors: "Hemant Jomraj, Bhavik Agarwal and Viktoria Rojkova",
        abstract: "Regulatory compliance question answering (QA) requires precise, verifiable information, and domain-specific expertise, posing challenges for Large Language Models (LLMs). In this work, we present a novel multi-agent framework that integrates a Knowledge Graph (KG) of Regulatory triplets with Retrieval-Augmented Generation (RAG) to address these demands. First, agents build and maintain ontology-free KG by extracting subject–predi- cate–object (SPO) triplets from regulatory documents and systematically cleaning, normalizing, deduplicating and updating them. Second, these triplets are embedded and stored along with their corresponding textual sections and metadata in a single enriched vector database, allowing for both graph-based reasoning and efficient information retrieval. Third, an orchestrated agent pipeline leverages triplet-level retrieval for question answering, ensuring high semantic alignment between user queries and the factual ’who-did-what-to-whom’ core captured by the graph. Our hybrid system outperforms conventional methods in complex regulatory queries, ensuring factual correctness with embedded triplets, enabling traceability through a unified vector database, and enhancing understanding through subgraph visualization, providing a robust foundation for compliance-driven and broader audit-focused applications."
    },
    {
        title: "Bridging Expert Knowledge and AI: A Semantic Architecture for Manufacturing Knowledge Management using Knowledge Graphs and Large Language Models",
        authors: "Camilla Hemmer",
        abstract: "Manufacturing companies face a critical knowledge management crisis where decades of operational expertise remains trapped in expert minds, leading to extended onboarding periods, inefficient decision-making and knowledge loss through retirement. This paper presents the development of a semantic AI assistant system that combines Knowledge Graphs with Large Language Models to transform how manufacturing engineers access and utilize institutional knowledge. The approach addresses the integration of scattered data across incompatible systems through a three-stage pipeline: multi-format document ingestion, knowledge graph construction, and LLM-enhanced natural language querying. Our implementation demonstrates how semantic technologies can address real-world industrial challenges, reducing information retrieval time and creating pathways for knowledge preservation at enterprise scale."
    }
];

export { industryTrack };