const inuseTrack = [
    {
        title: "Enhancing Transparency in Smart Grids: the SENSE Framework",
        authors: "Katrin Ehrenmüller, Konrad Diwold, Tobias Schwarzinger, Gernot Steindl, Wolfgang Prüggler, Fajar J. Ekaputra and Marta Sabou",
        abstract: "Modern power grids become ever more complex due to the integration of renewable energy sources and decentralized energy production, among other factors. This presents significant challenges for monitoring, diagnosing, and explaining grid anomalies. To address such setting, the SENSE framework generates contextualized, user-centred explanations of anomalous events in smart grids. To that end, it makes use of semantic web technologies in order to integrate sensor data with domain expert knowledge, to handle system events, and to derive relevant explanations. We evaluate SENSE in two use cases: a real-world smart charging garage and a simulated local energy community. Our evaluation shows that SENSE delivers accurate explanations, with an average accuracy of 82%, while being perceived as highly usable by domain experts. The results demonstrate the potential of semantic web technologies to increase transparency in smart grids leading to important, longer-term economic and environmental impacts."
    },
    {
        title: "Federated FAIR Semantic Artefacts Discovery and Search with OntoPortal Federation",
        authors: "Clement Jonquet, Syphax Bouazzouni, Guillaume Alviset, Nicola Fiore, Naouel Karam, Bilel Kihal, Christelle Pierkot, Martina Pulieri and Ilaria Rosati",
        abstract: "The explosion in the number of ontologies and semantic artefacts has come with the importance of developing Semantic Artefact Catalogues to support diverse research communities to harvest, share and serve these artefacts as FAIR objects. However, the lack of interoperability of these catalogues hampers cross disciplinary studies and make semantic stakeholders work quite cumbersome juggling back and forth from one tool to another. Here, we define Semantic Artefact Catalogues interoperability and report on three approaches studied. We present the implementation of the OntoPortal Fed-eration, i.e., the technical and collaboration processes engaged to federate multiple OntoPortal-based catalogues. We showcase how AgroPortal, EcoPortal, EarthPortal, and BiodivPortal, have been federated and now ena-ble federated browsing and search, facilitating seamless access to distribut-ed semantic artefacts and ontologies across their respective disciplines: agri-food, ecology, earth sciences and biodiversity. We discuss technical challenges and governance decisions and conclude by outlining future di-rections toward a sustainable and community-driven OntoPortal-based se-mantic layer for open science data infrastructures."
    },
    {
        title: "Open Government Data as Multi-dimensional 5 Star Data: cube.link",
        authors: "Michael Luggen, Benedikt Hitz, Julien Audiffren, Djellel Difallah, Jean-Luc Cochard and Philippe Cudre-Mauroux",
        abstract: "Many governments have made commitments to publish data collected and created by taxpayers as Open Government Data (OGD). Yet a common challenge is that data producers are not always the end-users, leading to inefficiencies, gaps, and inconsistencies in how data is used and interpreted. Data can be published at different levels of quality. For instance, smart cities can produce data collections via networks of sensors from power grids to transportation, whereas data extraction from documents can be highly noisy. A common pattern, however, is that this data describes spatio-temporal phenomena with multidimensional facets pertaining to real-world entities. Having a common ontology for such observations can help standardize their downstream usage. This paper introduces the effort made by the Swiss Government to create an ecosystem that allows one to publish open government data in a pragmatic and efficient manner, while maintaining the goal of publishing high-quality data that are integrated and interoperable. The paper introduces the domain-independent ontology RDF Cube Schema (https://cube.link), which is supported by open-source tools to publish, integrate, and validate diverse data sources, as well as multiple end-user tools for providing and visualizing data. With underlying statistics, we show the usage of these tools by both data providers and data consumers with two deployment use cases around the world."
    },
    {
        title: "Using Semantic Technologies in the Railway Domain: The Register of Infrastructure (RINF) System",
        authors: "Jhon Toledo, Daniel Doña, Edna Ruckhaus, Oscar Corcho, Marina Aguado, Dragos Patru, Ghislain Atemezing and Polymnia Vasilopoulou",
        abstract: "The European Union Agency for Railways (ERA) maintains the knowledge-graph-based “Register of Infrastructure (RINF) System”, based on a knowledge graph that follows an ontology (the ERA ontology), which is constructed using XML-to-RDF RML mappings, and validated using SHACL. Several applications consume this knowledge graph, allowing users to search for railway infrastructure elements, explore them on a map, and perform compatibility checks of railway vehicles on a certain route (in this case, with an additional knowledge graph that contains data from the European Register of Authorized Types of Vehicles - ERATV -). Data providers such as Infrastructure Managers (IMs) or National Registration Entities (NREs) can upload XML or RDF data, and Railway Undertakings (RUs) may receive notifications when changes are made to infrastructure elements in specific member states. As functionalities were added, challenges arose with respect to new ontology modeling requirements (based on legal requirements), propagation of changes in the semantic artifacts, URI design for RINF resources, harmonization of RINF and ERATV reference data, implementation and execution of mappings, and issues in the performance of SPARQL queries and SHACL validations. In this paper we describe the current status of the knowledge graph and applications, and reflect on the main challenges and lessons learned from this development and deployment."
    },
    {
        title: "Semantic-Aware Streaming Learning for Anomalous Event Detection in Power Grids",
        authors: "Lorenzo Iovine, Matteo Belcao, Giacomo Ziffer, Gabriele Paludetto and Emanuele Della Valle",
        abstract: "The growing adoption of smart grid technologies is turning power grids into data-rich environments, where continuous sensor streams capture complex and evolving operational states. Anomalous event detection in this context is particularly challenging due to the structural complexity of the grid and the non-stationary nature of sensor data. To address these challenges, we propose a semantic-aware approach that integrates real-time sensor streams with contextual information of the power grid, a knowledge graph (KG) as in International Electrotechnical Commission's standards. Our method employs Chimera, a semantic data analytics platform, and models capable of incremental learning and adaptation. We publish as open-data a comprehensive data-stream. We comparatively evaluate four scenarios: (1) only streaming events; (2) streaming events enriched with explicit features from the KG; (3) streaming events enriched with graph embeddings of KG's subgraphs; and (4) a combination of the last two. Experiments demonstrate the superior performances of models learned exploiting semantics in the KG."
    },
    {
        title: "A DataOps Toolbox Enabling Continuous Semantic Integration of Devices for Edge-Cloud AI Applications",
        authors: "Mario Scrocca, Marco Grassi, Alessio Carenini, Darko Anicic, Jean-Paul Calbimonte and Irene Celino",
        abstract: "The implementation of AI-based applications in complex environments often requires the collaboration of several devices spanning from edge to cloud. Identifying the required devices and configuring them to collaborate is a challenge relevant to different scenarios, like industrial shopfloor, road infrastructure, and healthcare therapy. We discuss the design and implementation of a DataOps toolbox leveraging Semantic Web technologies and a low-code mechanism to address heterogeneous data interoperability requirements in the development of such applications. The toolbox supports a continuous semantic integration approach to tackle various types of devices, data formats, and semantics, as well as different communication interfaces. The paper presents the application of the toolbox to three use cases from different domains, the DataOps pipelines implemented, and how they guarantee interoperability of static nodes' information and runtime data exchanges. Finally, we discuss the results from the piloting activities in the use cases and the lessons learnt."
    },
    {
        title: "Exploiting LLMs and Semantic Technologies to Build a Knowledge Graph of Historical Mining Data",
        authors: "Craig Knoblock, Binh Vu, Basel Shbita, Yao-Yi Chiang, Xiao Lin, Goran Muric, Pothula Punith Krishna, Jiyoon Pyo, Adriana Trejo-Sheu and Meng Ye",
        abstract: "To support data-driven decision-making in the assessment of critical mineral resources, we present Minmod, a large-scale knowledge graph built using semantic web technologies. Minmod integrates heterogeneous mining data from mining reports, scientific databases, and academic literature, modeling over 680,000 mineral site records across more than 190 commodities. Central to our approach is the use of ontologies and RDF representations to structure and unify data, enabling semantic interoperability and automated reasoning. We apply large language models (LLMs) to extract structured entities from unstructured sources, predict deposit types, and annotate tabular data with ontology-aligned semantics. Our system employs D-REPR to map diverse data sources into RDF and leverages SPARQL-compatible triple stores for querying and exploration. We use language models to perform high-precision entity resolution across datasets, and we demonstrate how semantic normalization supports applications such as mineral prospectivity mapping and grade-tonnage modeling. Minmod showcases the power of combining LLMs with semantic web principles to deliver a scalable, explainable, and reproducible framework for mineral resource intelligence."
    }
];

export { inuseTrack };